version: '3.7'

services:
  postgres:
    container_name: sunshop_db
    image: postgres:16.4
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
volumes:
  postgres:
    driver: local
